### ISSUE TITLE
youtube源频道建议

### ISSUE THREAD

**Issue by redrainl** [JMSTV/jmstv.github.io#1]
youtube源用的人多了，服务器容易顶不住，不如同时公布收集的youtube源链接，让有条件的可以用自己的服务器。

**Comment by showlee** [comment]
youtube源用的人多了，服务器容易顶不住，不如同时公布收集的youtube源链接，让有条件的可以用自己的服务器。

**Comment by JMSTV** [comment]
已上传YouTube链接，同时当前程序bug已修复，不会再无故停止崩溃。

**Comment by JMSTV** [comment]
end
